/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb787",
        "surface-tint": "#9b4500",
        "secondary-container": "#a3bdfe",
        "secondary": "#13336B",
        "tertiary-container": "#e58e52",
        "primary-fixed-dim": "#ffb68e",
        "on-surface": "#1b1c1c",
        "on-secondary-container": "#2f4b84",
        "on-primary-fixed-variant": "#763300",
        "on-surface-variant": "#584237",
        "tertiary-fixed": "#ffdcc7",
        "on-background": "#1b1c1c",
        "secondary-fixed": "#d9e2ff",
        "surface-container-highest": "#e4e2e2",
        "primary": "#9b4500",
        "on-primary-container": "#612900",
        "secondary-fixed-dim": "#afc6ff",
        "primary-container": "#FF7F27",
        "surface-dim": "#dbdad9",
        "on-secondary-fixed-variant": "#29457e",
        "on-secondary-fixed": "#001944",
        "inverse-on-surface": "#f2f0f0",
        "surface-bright": "#fbf9f9",
        "inverse-surface": "#303031",
        "tertiary": "#914c14",
        "outline": "#8b7265",
        "surface": "#fbf9f9",
        "primary-fixed": "#ffdbc9",
        "outline-variant": "#dfc0b1",
        "on-tertiary-fixed": "#311300",
        "surface-container-high": "#e9e8e7",
        "inverse-primary": "#ffb68e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#331200",
        "surface-variant": "#e4e2e2",
        "background": "#fbf9f9",
        "surface-container": "#efeded",
        "on-tertiary-container": "#5e2b00",
        "surface-container-low": "#f5f3f3",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#733600",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.125rem",
        "xl": "0.125rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
